### PR TITLE
Manually add Promise return in pair and unpair functions

### PR DESCRIPTION
**Pull request by alanzbl**

### CODE REVIEW

**Comment by obermillerk** [comment]
Hey, sorry it took me so long to look at this, but I'm a bit confused. What is the purpose of explicitly returning the promises? The functions are already async, so they return promises anyway.

**Comment by obermillerk** [comment]
Ah, I see your issue as well. I'll look into this tonight.

**Comment by obermillerk** [comment]
Hey, I believe I've addressed the issue. The latest is now on master, and it's released to npm as 0.2.2, see if that helps and let me know.

**Comment by obermillerk** [comment]
Hey @alanzbl, just checking in to see if you tried the new version? I think it should solve the issues you were having. Let me know either way if it works or not.

**Comment by alanzbl** [comment]
> Hey @alanzbl, just checking in to see if you tried the new version? I think it should solve the issues you were having. Let me know either way if it works or not.

Hey @obermillerk, thanks for checking back. I just tested it, and it works!!! 
An issue might not be related to this. I have access issue running unpair/pair during dev mode. but in build, it works

**Comment by obermillerk** [comment]
Glad it worked. Access issue? Not sure what you mean by that, but feel free to open up a new issue with more details and I'll see if I can fix that.

**Pull request closed without merging**
